name: Notifications
on: [push]

irc_settings: &irc_settings
  channel: "#notifications_test"
  nickname: Neferus
  server: irc.guildofwriters.org 
  port: 6667
  tls: false

jobs:
  notification:
    runs-on: ubuntu-latest
    name: IRC Notifications

    steps:
      - name: Notification
        uses: rectalogic/notify-irc@v1
        with:
          <<: *irc_settings  
          message: |-
            ${{ github.actor }} pushed to ${{ github.event.repository.full_name }}: ${{ github.event.compare }}
