name: "IRC Notifications"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, closed, ready_for_review]

env:
  channel: "#notifications_test"
  nick: Neferus
  notice: false
  server: irc.guildofwriters.org 
  port: 6667
  tls: false

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - name: Push
        if: github.event_name == 'push'
        uses: rectalogic/notify-irc@v1
        with:
          channel: ${{ env.channel }}
          nickname: ${{ env.nick }}
          notice: ${{ env.notice }}  
          server: ${{ env.server }} 
          port: ${{ env.port }}
          tls: ${{ env.tls }}
          message: |-
            ${{ github.actor }} has pushed to ${{ github.repository }}: ${{ github.event.compare }}.
          
      - name: PR Opened
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: rectalogic/notify-irc@v1
        with:
          channel: ${{ env.channel }}
          nickname: ${{ env.nick }}
          notice: ${{ env.notice }}  
          server: ${{ env.server }} 
          port: ${{ env.port }}
          tls: ${{ env.tls }}
          message: |-  
            ${{ github.actor }} has opened pull request #${{ github.event.number }}: ${{ github.event.pull_request.html_url }}.
              
      - name: PR Closed
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && !github.event.pull_request.merged
        uses: rectalogic/notify-irc@v1
        with:
          channel: ${{ env.channel }}
          nickname: ${{ env.nick }}
          notice: ${{ env.notice }}  
          server: ${{ env.server }} 
          port: ${{ env.port }}
          tls: ${{ env.tls }}
          message: |-
            ${{ github.actor }} has closed pull request #${{ github.event.number }}: ${{ github.event.pull_request.html_url }}.
            
      - name: PR Merged
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged
        uses: rectalogic/notify-irc@v1
        with:
          channel: ${{ env.channel }}
          nickname: ${{ env.nick }}
          notice: ${{ env.notice }}  
          server: ${{ env.server }} 
          port: ${{ env.port }}
          tls: ${{ env.tls }}
          message: |-
            ${{ github.actor }} has merged pull request #${{ github.event.number }}: ${{ github.event.pull_request.html_url }}.
