name: CI

on: [push]

jobs:
  notification:
    runs-on: ubuntu-latest
    name: IRC Notifications

    steps:
      - name: Notification
        uses: rectalogic/notify-irc@v1
        with:
          channel: ''##notifications_test'
          nickname: Neferus
          server: guildofwriters.org 
          port: 6667  
          message: |-
            ${{ github.actor }} pushed to ${{ github.event.repository.full_name }}: ${{ github.event.compare }}
