name: Notifications
on: [push]

env:
  CHANNEL: "#notifications_test"
  NICK: Neferus
  SERVER: irc.guildofwriters.org 
  PORT: 6667
  TLS: false

jobs:
  notification:
    runs-on: ubuntu-latest
    name: IRC Notifications

    steps:
      - name: Notification
        uses: rectalogic/notify-irc@v1
        with:
          channel: $CHANNEL
          nickname: $NICK
          server: $SERVER 
          port: $PORT
          tls: $TLS
          message: |-
            ${{ github.actor }} pushed to ${{ github.event.repository.full_name }}: ${{ github.event.compare }}
