name: Notifications
on: [push]

env:
  channel: "#notifications_test"
  nick: Neferus
  notice: true 
  server: irc.guildofwriters.org 
  port: 6667
  tls: false

jobs:
  notification:
    runs-on: ubuntu-latest
    name: IRC Notifications

    steps:
      - name: Notification
        uses: rectalogic/notify-irc@v1
        with:
          channel: ${{ env.channel }}
          nickname: ${{ env.nick }}
          notice: ${{ env.notice }}  
          server: ${{ env.server }} 
          port: ${{ env.port }}
          tls: ${{ env.tls }}
          message: |-
            ${{ github.actor }} pushed to ${{ github.event.repository.full_name }}: ${{ github.event.compare }}
